---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-stub-status
data:
  status.conf: |
    server {
      listen 80 default_server;
      server_name _;
      location / {
        return 200 'vasya\n';
      }
      location = /basic_status {
        stub_status;
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.6
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
          name: status-location
      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:0.8.0
        ports:
        - containerPort: 9113
        args:
        - -nginx.scrape-uri=http://localhost/basic_status
      volumes:
      - name: status-location
        configMap:
          name: nginx-stub-status
          items:
          - key: status.conf
            path: default.conf

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  ports:
  - name: web
    port: 80
    targetPort: 80
  - name: metrics
    port: 9113
  selector:
    app: nginx
