apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - image: docker.io/346245737637245/shopper-payment:2
        name: paymentservice
        env:
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "vasya:9091"
        - name: CURRENCY_SERVICE_ADDR
          value: "vasya:9093"
        - name: CART_SERVICE_ADDR
          value: "vasya:9094"
        - name: RECOMMENDATION_SERVICE_ADDR
          value: "vasya:9095"
        - name: SHIPPING_SERVICE_ADDR
          value: "vasya:50051"
        - name: CHECKOUT_SERVICE_ADDR
          value: "vasya:5050"
        - name: AD_SERVICE_ADDR
          value: "vasya:9555"
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
